repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: requirements-txt-fixer
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
    -   id: ruff
    -   id: ruff-format
