first_names = [
    "Rey",
    "Sleve",
    "Onson",
    "Darryl",
    "Glenallen",
    "Mario",
    "Raul",
    "Kevin",
    "Tony",
    "Vinny",
    "Bobson",
    "Willie",
    "Jeromy",
    "Scott",
    "Shown",
    "Dean",
    "Mike",
    "Mik",
    "Dwigt",
    "Todd",
    "Tim",
    "Karl",
]

last_names = [
    "McDichael",
    "Sweemey",
    "Archideld",
    "Smorin",
    "McSriff",
    "MacGruff",
    "Mixon",
    "Chamgerlain",
    "Nogilny",
    "Smehrik",
    "Dugnutt",
    "Dustice",
    "Gride",
    "Dourove",
    "Furcotte",
    "Wesrey",
    "Truk",
    "Rortugal",
    "Sandael",
    "Dandelton",
    "Sernandez",
    "Bonzalez",
    "Buster",
    "Jamari",
]

time_measurements = [
    "nights",
    "years",
    "weeks",
    "months",
    "moons",
    "fortnights",
    "Juneteenths",
    "country moons",
    "Sidereal days",
    "dog years",
]

weird_shoes_urls = [
    "https://www.amazon.com/Poulaines-Leather-Curved-Renaissance-Cosplay/dp/B0CSF1RWBQ/ref=asc_df_B0CSF1RWBQ/?tag=hyprod-20&linkCode=df0&hvadid=708144672471&hvpos=&hvnetw=g&hvrand=74891359273654179&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9009844&hvtargid=pla-2367630436234&psc=1&mcid=e2ecf3033b7c304294b7bc4802a3fbf0",
    "https://www.temu.com/kuiper/un9.html?subj=goods-prm-un&_bg_fs=1&_p_jump_id=1067&_x_vst_scene=adg&sku_id=17592364226151&goods_id=601099551744464&adg_ctx=a-32387edb~c-db9d2aa5~f-3ba963bb&_x_ads_sub_channel=shopping&_p_rfs=1&_x_ns_prz_type=-1&_x_ns_sku_id=17592364226151&_x_ns_gid=601099551744464&mrk_rec=1&_x_ads_channel=google&_x_gmc_account=647900107&_x_login_type=Google&_x_ads_account=1919904652&_x_ads_set=21513236537&_x_ads_id=165642994015&_x_ads_creative_id=707289116394&_x_ns_source=g&_x_ns_gclid=CjwKCAjwodC2BhAHEiwAE67hJE5Uep9rjXZglbJopxmF2GWRZwOrDU4TusZL2QHT_6Q4-QkzFlPPnBoCZOcQAvD_BwE&_x_ns_placement=&_x_ns_match_type=&_x_ns_ad_position=&_x_ns_product_id=17592364226151&_x_ns_target=&_x_ns_devicemodel=&_x_ns_wbraid=Cj4KCAjw_sq2BhBsEi4AV_CU9amks703Ej9zGJyhMUloBxMkWn11olZETwylByS6Bh6Ipla4NuKqqRSjGgJS5g&_x_ns_gbraid=0AAAAAo4mICEjYmZeGaaoYFmnVINyQ-wdp&_x_ns_targetid=pla-2330597633908&gad_source=1&gclid=CjwKCAjwodC2BhAHEiwAE67hJE5Uep9rjXZglbJopxmF2GWRZwOrDU4TusZL2QHT_6Q4-QkzFlPPnBoCZOcQAvD_BwE",
    "https://walterdixxon.com/products/the-dorado-patent-leather-studded-pointed-toe-dress-shoes?currency=USD&variant=44876407013609&utm_source=google&utm_medium=cpc&utm_campaign=Google%20Shopping&stkn=266b2c0aaede&tw_source=google&tw_adid=&tw_campaign=18134283587&gad_source=1&gclid=CjwKCAjwodC2BhAHEiwAE67hJJovNUFsjBADCe8dfpN4Ofs6ZobgluI8IA1tDdhUgklhI8DAJ5WBLBoCMokQAvD_BwE",
    "https://www.etsy.com/listing/1400637692/sapato-de-palhaco-banana?gpla=1&gao=1&&utm_source=google&utm_medium=cpc&utm_campaign=shopping_us_a-clothing-other&utm_custom1=_k_CjwKCAjwodC2BhAHEiwAE67hJJBL7yq-E1p7E6becW9nQpD2QlYsqnBuREp5XD_uMcaKsZVPv-f5xBoCG1wQAvD_BwE_k_&utm_content=go_21500568414_164860976149_707557561667_aud-2191767825281:pla-297616371983_c__1400637692_12768591&utm_custom2=21500568414&gad_source=1&gclid=CjwKCAjwodC2BhAHEiwAE67hJJBL7yq-E1p7E6becW9nQpD2QlYsqnBuREp5XD_uMcaKsZVPv-f5xBoCG1wQAvD_BwE",
    "https://www.bondagefetishstore.com/p/SPL-GLAM02.html?gclid=CjwKCAjwodC2BhAHEiwAE67hJAEyGFqxJg55nGxxlZdp_XOAKjx2FK3i0dG-jeHhPRGYD2RKKVrCdxoCpWkQAvD_BwE",
    "https://queerintheworldshop.com/products/rainbow-snakeskin-wing-tip-dress-shoes?currency=USD&variant=43925961900252&utm_source=google&utm_medium=cpc&utm_campaign=Google%20Shopping&stkn=d4b7c19d2d2e&gad_source=1&gclid=CjwKCAjwodC2BhAHEiwAE67hJMXkmp7y4P8zjbxi6RqWVpckWVzBlZKKdw43bvcqiOUiunVg0fXoIRoCr5EQAvD_BwE",
    "https://crocodilewear.com/products/cowboyluxe-embroidered-leather-dress-loafers?currency=USD&variant=40505682296886&utm_source=google&utm_medium=cpc&utm_campaign=Google%20Shopping&stkn=77d664eac709&utm_source=&utm_medium=&gad_source=1&gclid=CjwKCAjwodC2BhAHEiwAE67hJPA6JnGmW8jjCOwTJKDKT8RwwG2hnHe3U_DJUfGbuyy138B5TCT_DhoCCncQAvD_BwE",
]

random_colors = [
    "tangerine",
    "periwinkle",
    "sarcoline",
    "feldgrau",  # Yikes!
    "gamboge",
    "eburnean",
    "amaranth",
    "vantablack",
    "bastard-amber",
    "drakes-neck",
    "gingerline",
    "lusty gallant",
    "pervenche",
    "sang-de-boeuf",
    "sinoper",
    "watchet",
    "verditer",
    "filemot",
    "eau-de-nil",
    "rufous",
    "fulvous",
    "wenge",
    "xanadu",
    "phlox",
]

random_animals = [
    "walrus",
    "capybara",
    "jaguar",
    "anaconda",
    "tapir",
    "warthog",
    "wild hog",
    "zebra",
    "gazelle",
    "clydesdale",
    "racoon",
    "meerkat",
    "capuchin",
    "squirrel monkey",
    "sloth",
    "sea turtle",
    "baboon",
    "southern maple bear",
    "gibbon",
    "hippo",
    "water buffalo",
]

kind_of_shoes = [
    "pilgrim shoes",
    "derbies",
    "basketball shoes",
    "oxfords",
    "monkstrap shoes",
    "chukkas",
    "sneakers",
    "boots",
    "loafers",
    "crocs",
    "clogs",
    "sandals",
    "emperor slippers",
    "mountain boots",
    "monk shoes",
    "Jordans",
]

shoe_parts = [
    "tassels",
    "buckles",
    "rims",
    "laces",
    "rubber",
    "leather",
    "medallions",
    "gems",
    "crystals",
]

sports_teams = [
    "Royals",
    "Reds",
    "Twins",
    "Oilers",
    "Vancouver Honey Trees",
    "Sycamores",
    "Yankees",
    "Knicks",
    "Rangers",
    "Kings",
    "Cowboys",
    "Texans",
    "Rams",
    "Eagles",
    "Phillies",
    "Manchester United",
    "Orioles",
    "Nets",
    "Lakers",
    "Clippers",
    "Flyers",
    "Penguins",
    "Super Sonics",
    "Saskatchewan Roughriders",
    "Toronto Argonauts",
]

weird_currencies = [
    "doubloons",
    "pieces of eight",
    "Bitcoin",
    "rai stones",
    "Dogecoin",
    "Ethereum",
    "travelers checks",
    "coins",
    "Brunei dollars",
    "nakfas",
    "quetzals",
    "Jersey pounds",
    "ouguiyas",
    "kinas",
]

store_links = [
    "https://www.jfitzpatrickfootwear.com/products/crescent-sangria-calf",
    "https://www.jfitzpatrickfootwear.com/products/alder-black-calf",
    "https://www.jfitzpatrickfootwear.com/products/alki-black-calf",
    "https://www.jfitzpatrickfootwear.com/products/whatcom-black-calf",
    "https://www.jfitzpatrickfootwear.com/products/fremont-black-marble-patina",
]

random_locations = [
    "Brazil",
    "Papua New Guinea",
    "Pakistan",
    "Missouri",
    "Faroe Islands",
    "Falkland Islands",
    "Seychelles",
    "Madagascar",
    "Tunisia",
    "Lincoln",
    "Gaza",
    "Golan Heights",
    "West Bank",
    "Macau",
    "Tripoli",
    "Kiev",
    "Crimea",
    "Donetsk",
    "Montana",
    "Vermont",
    "Omaha",
    "Solomon Islands",
    "Venice Beach",
]

show_locations = [
    "Brazil",
    "Omaha",
    "Venezuela",
    "Cuba",
    "Oklahoma City",
    "Canton",
    "New Jersey",
    "Manhattan",
    "Argentina",
    "Chile",
]
